language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - master
  - nightly

matrix:
  allow_failures:
    - php: master
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer install --no-interaction

script:
  - phpunit --coverage-clover=coverage.xml
  - composer phan
  - composer phpcs
  - composer phpcbf
  - composer phpmnd
  - composer churn
  - composer phpstan
  - composer phpmd
  - composer infection
  - composer psalm

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
